name: Build MTVehicles

on:
  push:
    branches: [ "allow-server-v1.21.11", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: MTVehicles-jar
          path: target/*.jar
